name: Load Raw Data like artifact to wandb

on:
  push:
    branches:
      - master
    paths:
      - 'src/data/load.py'

jobs:
  load_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run load.py and log to wandb
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: python src/data/load.py --IdExecution ${{ github.run_number }}
